name = "PEPS"
uuid = "8660e2f9-29a6-4db9-bbe4-0c34d68c8cc8"
authors = ["Katharine Hyatt <khyatt@flatironinstitute.org>"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
